routes/web.php
<?php
//get
Route::get("/", 'FrontPageController@index')->name("home");
Route::get("/index.html", 'FrontPageController@index');
//Route::get('/blog','FrontPageController@blog')->name('blog');

//post
Route::post('/booking','BookingController@sendBooking')->name('send_booking');
Route::post('/contact', 'ContactController@send')->name("sendcontact");
//auth
Auth::routes();
Route::group(['middleware' => ['web', 'auth']], function () {
	Route::get('/backend', 'PostController@dashboard')->name('dashboard');
	Route::resource('backend/meta', 'MetaController');
	Route::resource('backend/cars', 'CarController');
	Route::resource('backend/team_members', 'TeamMemberController');
	//Route::resource('backend/posts', 'ArticleController');
	//Articles
    Route::get('backend/posts','ArticleController@index')->name("posts.index");
    Route::get("backend/posts/create", 'ArticleController@create')->name('posts.create');
    Route::post("backend/posts/store",'ArticleController@store')->name("posts.store");
    Route::get("backend/posts/data", 'ArticleController@data')->name("posts.data");
    Route::get('backend/posts/{id}/edit',"ArticleController@edit")->name('posts.edit');
    Route::get('backend/posts/show/{id}', 'ArticleController@show')->name('posts.show');
    Route::put('backend/posts/update/{id}',"ArticleController@update")->name('posts.update');
	Route::delete('backend/posts/delete/{id}',"ArticleController@destroy")->name('posts.delete');
	//Clients
    Route::get('backend/clients','ClientController@index')->name("clients.index");
    Route::get("backend/clients/create", 'ClientController@create')->name('clients.create');
    Route::post("backend/clients/store",'ClientController@store')->name("clients.store");
    Route::get("backend/clients/data", 'ClientController@data')->name("clients.data");
    Route::get('backend/clients/{id}/edit',"ClientController@edit")->name('clients.edit');
    Route::get('backend/clients/show/{id}', 'ClientController@show')->name('clients.show');
    Route::put('backend/clients/update/{id}',"ClientController@update")->name('clients.update');
    Route::delete('backend/clients/delete/{id}',"ClientController@destroy")->name('clients.delete');
    //Category
	Route::resource('backend/categories', 'CategoryController');
	//Contact Listing
	Route::get('backend/contact-listing', 'ContactController@index')->name('contact-list');
	//Route::get('/contact-listing', 'ContactController@index')->name("contact-list");
	Route::delete('backend/contact/{id}', 'ContactController@destroy')->name('contact-destory');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
   public $fillable = ['article_title','author_name','category_id','feature_image','article_body'];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use App\Category;
use Datatables;
use DB;
use Image;

class ArticleController extends Controller
{
    public function __construct() {
        $this->middleware('auth')->except('index', 'show');
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('articles.indexDatable',compact('get_all_articles'));
    }

    /**
     * Process datatables ajax request.
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function data()
    {
        $get_all_articles = Article::select(['id', 'name', 'email', 'password', 'created_at', 'updated_at']);
        return Datatables::of(Article::query())->addColumn('action', function ($get_all_articles) 
                            {
                                return '<a href="posts/show/'.$get_all_articles->id.'" class="btn btn-md btn-primary"><i class="glyphicon glyphicon-eye-open"></i> View More</a>';
                            })
                            ->editColumn('id', 'ID: {{$id}}')
                            ->make(true);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories=Category::all();
        return view('articles.create',compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validating title and body field
        $this->validate($request, [
            'article_title'=>'required|max:100',
            'author_name'=>'max:100',
            'category_id'=>'required|integer|max:500',
            'article_body' => 'required',
            'feature_image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048|dimensions:min-width=720,min-height=350'
            ]);
        //put request value in variables
        $article_title       = $request['article_title'];
        $author_name         = $request['author_name'];
        $category_name       = $request['category_id'];
        $article_body        = $request['article_body'];
        //creating the request
        $article = Article::create($request->only('article_title', 'author_name','category_id','article_body'));
        // Check if file is present
        if( $request->hasFile('feature_image') ) {
            $feature_image     = $request->file('feature_image');
            $filename      = time() . '.' . $feature_image->getClientOriginalExtension();
            Image::make($feature_image)->save( public_path('uploads/blog_feature_img/' . $filename ) );
            $article->feature_image = $filename;
        }
        $article->save();
        return redirect()->route('posts.index')->with('flash_message', 'Articles,'. $article->article_title.' created');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $categories=Category::all();
        $article = Article::findOrFail($id); //Find post of id = $id
        return view ('articles.show', compact('article','categories'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
    	$categories=Category::all();
        $article = Article::findOrFail($id);
        return view('articles.edit',compact('article','categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'article_title'=>'required|max:100',
            'author_name'=>'max:100',
            'category_id'=>'required|integer|max:500',
            'article_body' => 'required',
            'feature_image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048|dimensions:min-width=720,min-height=350'
            ]);
        //put request value in variables
        $article = Article::findOrFail($id);
        $article_title       = $request['article_title'];
        $author_name         = $request['author_name'];
        $category_id       	 = $request['category_id'];
        $article_body        = $request['article_body'];
        //asign to query
        $article->article_title = $request->input('article_title');
        $article->author_name = $request->input('author_name');
        $article->category_id = $request->input('category_id');
        $article->article_body = $request->input('article_body');
        // Check if file is present
        if( $request->hasFile('feature_image') ) {
            $feature_image     = $request->file('feature_image');
            $filename      = time() . '.' . $feature_image->getClientOriginalExtension();
            Image::make($feature_image)->save( public_path('uploads/blog_feature_img/' . $filename ) );
            $article->feature_image = $filename;
        }
        $article->save();
        return redirect()->route('posts.index', $article->id)->with('flash_message', 'Current Article, '. $article->article_title.' been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::findOrFail($id);
        //dd($article);
        $article->delete();
        return redirect()->route('posts.index')
                         ->with('flash_message','Article  has been successfully deleted');
    }
}

resources/views/articles/create.blade.php
@extends('backend.backend')

@section('title', '| Add New Articles')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">

        <h1>Add New Article </h1>
        <hr>

    {{-- Using the Laravel HTML Form Collective to create our form --}}
        {{ Form::open(array('route' => 'posts.store','enctype'=>'multipart/form-data')) }}
        <div class="form-group ">
            {{ Form::label('article_title', 'Article Title') }}
            {{ Form::text('article_title', null, array('class' => 'form-control','placeholder'=>'Please Enter Article Title')) }}
            <br>

            {{ Form::label('author_name', 'Author Name') }}
            {{ Form::text('author_name', null, array('class' => 'form-control' ,'placeholder'=>'Type Your Name')) }}
            <br>
            
            {{ Form::label('category_name', 'Category Name') }}
            <select name="category_id" class="form-control">
		      @foreach($categories as $category)
		      <option value="{{$category->id}}">{{$category->category_name}}</option>
		      @endforeach
		  	</select> 
            <br><br>

            {{ Form::label('feature_image', 'Upload Feature Image') }}
            {{ Form::file('feature_image', null, array('class' => 'form-control')) }}
            <p ><strong class="text-danger">Feature Image must be 720px x 350px Dimentions at last.</strong></p>
            <br>

             {{ Form::label('article_body', 'Article Text') }}
             {{ Form::textarea('article_body', null, array('class' => 'form-control','id'=>'article_body')) }}<br>


            {{ Form::submit('Add New Article', array('class' => 'btn btn-success btn-lg btn-block')) }}
            {{ Form::close() }}
        </div>
        </div>
    </div>
		@push('scripts')
		<script src="{{ asset('js/summernote/summernote.js')}}"></script>
		<script>
		$(document).ready(function() {
		  $('#article_body').summernote();
		});
		</script>
		@endpush


@endsection

resources/views/articles/edit.blade.php
@extends('backend.backend')

@section('title', '| Edit Articles')

@section('content')
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
        <h1>Edit Article </h1>
        <hr>
    {{-- Using the Laravel HTML Form Collective to create our form --}}
        {{ Form::model($article, array('route' => array('posts.update', $article->id), 'method' => 'PUT', 'enctype'=>'multipart/form-data')) }}
        <div class="form-group ">
            {{ Form::label('article_title', 'Article Title') }}
            {{ Form::text('article_title', null, array('class' => 'form-control')) }}<br>
            <br>

            {{ Form::label('author_name', 'Author Name') }}
            {{ Form::text('author_name', null, array('class' => 'form-control' ,'placeholder'=>'Type Your Name')) }}
            <br>
            
            {{ Form::label('category_name', 'Category Name') }}
            <select name="category_id" class="form-control">
		      @foreach($categories as $category)
		      <option value="{{$category->id}}">{{$category->category_name}}</option>
		      @endforeach
		  	</select> 
            <br><br>

            {{ Form::label('feature_image', 'Upload Feature Image') }}
            {{ Form::file('feature_image', null, array('class' => 'form-control')) }}
            <p ><strong class="text-danger">Feature Image must be 720px x 350px Dimentions at last.</strong></p>
            <br>

             {{ Form::label('article_body', 'Article Text') }}
             {{ Form::textarea('article_body', null, array('class' => 'form-control','id'=>'article_body')) }}<br>


            {{ Form::submit('Update Article', array('class' => 'btn btn-success btn-lg btn-block')) }}
            {{ Form::close() }}
        </div>
        </div>
    </div>
		@push('scripts')
		<script src="{{ asset('js/summernote/summernote.js')}}"></script>
		<script>
		$(document).ready(function() {
		  $('#article_body').summernote({
            height: '300px'
          });
		});
		</script>
		@endpush


@endsection

resources/views/articles/index.blade.php
@extends('backend.backend')
@section('content')
    {{-- <div class="container"> --}}
        <div class="row">
            <div class="col-md-10 col-md-offset-1">

                <div class="panel panel-default">
                    <div class="panel-heading"><h3>Article List<a href="{{ route('categories.create')}}" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Crate Category</a></h3></div>
                        <div class="panel-body">
                            <li style="list-style-type:none;border: 1px solid #eaeaea; padding: 0px 20px; padding-top: 10px;">
                                <div class="row">
                                    <div class="col-md-12">
                                        <table class="table table-bordered text-center">
                                            <tr class="text-center">
                                                <th class="text-center">ID</th>
                                                <th class="text-center">Title</th>
                                                <th class="text-center">Feature Image</th>
                                                <th class="text-center">Post at</th>
                                                <th class="text-center">Actions</th>
                                            </tr>
                                            @foreach ($get_all_articles as $get_all_article)
                                            <tr>
                                                <td>{{  $get_all_article->id }}</td>
                                                <td>{{  $get_all_article->article_title }}</td>
                                                <td>{{  $get_all_article->feature_image }}</td>
                                                <td>{{  $get_all_article->updated_at }}</td>
                                                {{ Form::open([ 'method' => 'delete', 'route' => ['posts.destroy', $get_all_article->id ], 'onsubmit' => 'return ConfirmDelete()']) }}
                                                <td><a href="{{ route('posts.edit', $get_all_article->id) }}" class="btn btn-warning" >Edit</a>
                                                    {{ Form::submit('Delete', ['class' => 'btn btn-danger']) }}
                                                    {{ Form::close() }}
                                                     <script>
                                                        function ConfirmDelete(){
                                                        return confirm('Are you sure to delete ?');
                                                        }
                                                    </script>



                                                
                                            </tr>
                                            @endforeach
                                            
                                        </table>
                                        
                                    </div>
                                </a>
                                </div>

                            </li>
                        </div>
                    
                    </div>
                    <div class="text-center">
                        {!! $get_all_articles->links() !!}
                    </div>

                </div>
            </div>
{{--         </div> --}}
@endsection

resources/views/articles/indexDatable.blade.php
 @extends('backend.backend')
@section('content')
<div class="col-md-12">
    <h1>Article Lists <a href="{{ URL::to('backend/posts/create') }}" class="btn btn-success btn-lg pull-right">Add New Article</a></h1>
    <hr>
</div>

    <table class="table table-bordered " id="articles-table">
        <thead class="">
            <tr>
                <th>Id</th>
                <th>Article_Title</th>
                <th>Author Name</th>
                <th>Category</th>
                <th>Feature Img</th>
                <th>Last Update</th>
                <th>Actions</th>
            </tr>
        </thead>
</table>
@push('scripts')
<script>
$(function() {
    $('#articles-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{!! route('posts.data') !!}',
        columns: [
            { data: 'id', name: 'id' },
            { data: 'article_title', name: 'article_title' },
            { data: 'author_name', name: 'author_name' },
            { data: 'category_id', name: 'category_id' },
            { data: 'feature_image', name: 'feature_image' },
            { data: 'updated_at', name: 'updated_at' },
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
});
</script>
@endpush
@endsection








 

resources/views/articles/show.blade.php
@extends('backend.backend')
@section('title', '| Article Detail')
@section('content')
                  <div class="container">
                  	<div class="col-md-12">	
                  		<h1>
                  			{{ $article->article_title }}
                  			<div class="pull-right" role="group" > 
                  			 {!! Form::open(['method' => 'DELETE', 'route' => ['posts.delete', $article->id]]) !!}                               
                  			 <a href="{{ route('posts.index') }}" class="btn btn-default">Back</a>
							           <a href="{{ route('posts.edit', $article->id) }}" class="btn btn-info">Edit</a>
							           {!! Form::submit('Delete', ['class' => 'btn btn-danger','id' => 'carDelete','onsubmit' => 'ConfirmDelete()']) !!}
							         </div>
                  		</h1>
                  		 <hr>
                        <span class="label label-primary"> Author Name : {{ $article->author_name }}</span>
                        @foreach($categories as $category)
                          <span class="label label-success"> Category : {{ $category->category_name }}</span>
                        @endforeach
                        <span class="label label-info"> Last Update :{{ $article->updated_at }}</span >
                        <hr>
                  	</div>
                  	<div class="col-md-12">
                  		<div class="blog_img_wrap img-responsive">
                  		@if( ! empty($article->feature_image))
                             <img src="/uploads/blog_feature_img/{{ $article->feature_image }}" alt="{{ $article->article_title }}" class="img-responsive"  style="height: 300px; width: 100%;"/>
                        @else
                             <img src="{{asset('images/cars/03.jpg')}}" class="img-responsive"/>
                        @endif
                       
                        </div>
                  	</div>
                  	<div class="col-md-12">	
	                  	 <p>{!! $article->article_body !!}</p>
                    </div>
                  </div>
@endsection